# -*- mode: ruby -*- #에디터에 현재 파일이 루비임을 인색하게 하는 호환 코드 
# vi: set ft=ruby :  #ft는 file type의 약자, 해당 내용은 실행에 영향을 미치지 않음

Vagrant.configure("2") do |config|   # 2: 베이그런트에서 루비로 코드를 읽어 들여 실행할 때 작동하는 api 버전
  config.vm.define "m-k8s" do |cfg|   # 버추얼 박스에서 보이는 가상 머신을 "m-k8s"로 정의,  do |cfg|를 추가해 원하는 설정으로 변경
  # do |이름| -> end로 종료함
    cfg.vm.box = "sysnet4admin/CentOS-k8s" # 가상 머신의 박스를 sysnet4admin/CentOS-k8s로 설정
    cfg.vm.box_version = "0.8.0"
    cfg.vm.provider "virtualbox" do |vb| # 베이그런트의 프로바이더가 버추얼박스임을 정의
      #프로바이더: 베이그런트를 통해 제공되는 코드가 실제로 가상 머신으로 배포되게 하는 소프트웨어
      #해당 설정은 vb로 정의
      vb.name = "m-k8s(github_SysNet4Admin)"  #가상 머신의 이름
      vb.cpus = 2  # cpu 개수
      vb.memory = 2048  # 메모리 크기
      vb.customize ["modifyvm", :id, "--groups", "/k8s-SM(github_SysNet4Admin)"]  #소속된 그룹
    end
    cfg.vm.host_name = "m-k8s"  #호스트 이름 설정
    cfg.vm.network "private_network", ip: "192.168.1.10"  #호스트 전용 네트워크를 프라이빗 네트워크로 설정
    # 즉, 인터페이스를 호스트 전용으로 구성, ip는 192.168.1.10로 지정

    cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
    # ssh 통신은 호스트 60010번이 게스트 22번으로 전달되도록 구성
    # auto_correct: true    ->     포트가 중복되면 포트를 자동으로 변경되게 설정
    # 호스트 (pc), 게스트 (가상머신)

    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    # 호스트와 게스트 사이에 동기화가 이뤄지지 않게 설정 (disabled: true)

    cfg.vm.provision "shell", path: "install_pkg.sh" # 프로비저닝 스크립트 추가
    # path에 있는 install_pkg.sh를 게스트(centOS) 내부에서 실행하도록 함
    
    cfg.vm.provision "file", source: "ping_2_nds.sh", destination: "ping_2_nds.sh" # 파일을 게스트에 복사
    # source에 있는 ping_2_nds.sh를 게스트에 복사하여 실행하도록 함
    # 게스트의 home 디렉토리에 ping_2_nds.sh를 복사하도록 함

    cfg.vm.provision "shell", path: "config.sh" # 프로비저닝 스크립트 추가 (config.sh 실행)

  end

  #=============#
  # Added Nodes #
  #=============#

  # Nodes (추가한 3대의 CentOS 가상 머신을 정의)
  # 각각의 가상 머신은 w1-k8s, w2-k8s, w3-k8s로 정의
  (1..3).each do |i|
    config.vm.define "w#{i}-k8s" do |cfg|
      cfg.vm.box = "sysnet4admin/CentOS-k8s"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "w#{i}-k8s(github_SysNet4Admin)"
        vb.cpus = 1
        vb.memory = 1024
        vb.customize ["modifyvm", :id, "--groups", "/k8s-SM(github_SysNet4Admin)"]
      end
      cfg.vm.host_name = "w#{i}-k8s"
      cfg.vm.network "private_network", ip: "192.168.1.10#{i}"
      cfg.vm.network "forwarded_port", guest: 22, host: "6010#{i}",auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
      cfg.vm.provision "shell", path: "install_pkg.sh"
    end
  end



end
